{{- if .Values.calckey.separateWorker }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "calckey.fullname" . }}-config-worker
  labels:
    {{- include "calckey.labels" . | nindent 4 }}
type: Opaque
data:
  default.yml: {{ include "calckey.config.worker" . | b64enc }}
{{- end }}
