apiVersion: v1
kind: Service
metadata:
  name: {{ include "calckey.fullname" . }}
  labels:
    {{- include "calckey.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "calckey.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
