apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "activityrelay.fullname" . }}
  labels:
    {{- include "activityrelay.labels" . | nindent 4 }}
data:
  relay.yaml: |-
    db: /data/relay.jsonld
    listen: 0.0.0.0
    port: 8080
    note: "{{ .Values.config.note }}"
    push_limit: {{ .Values.config.push_limit }}
    ap:
    {{- toYaml .Values.config.ap | nindent 6 }}
    cache:
    {{- toYaml .Values.config.cache | nindent 6 }}
