{{- if .Values.certificate.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "aoderelay.fullname" . }}
  labels:
    {{- include "aoderelay.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.certificate.spec | nindent 2 }}
{{- end }}
