{{- if .Values.persistence.enabled -}}
{{- if not .Values.persistence.existingClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if .Values.persistence.annotations }}
  annotations:
{{ toYaml .Values.persistence.annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "aoderelay.labels" . | nindent 4 }}
  name: {{ include "aoderelay.fullname" . }}
spec:
  accessModes:
{{ toYaml .Values.persistence.accessModes | indent 4 }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- if .Values.persistence.volumeBindingMode }}
  volumeBindingMode: "{{ .Values.persistence.volumeBindingMode }}"
{{- end }}
  resources:
    requests:
      storage: "{{ .Values.persistence.size }}"
{{- if .Values.persistence.selector }}
  selector:
  {{- toYaml .Values.persistence.selector | nindent 4 }}
{{- end -}}
{{- if .Values.persistence.volumeName }}
  volumeName: "{{ .Values.persistence.volumeName }}"
{{- end -}}
{{- end -}}
{{- end -}}
