apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aoderelay.fullname" . }}
  labels:
    {{- include "aoderelay.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.config.apiToken }}
  API_TOKEN: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.config.telegramHandle }}
  TELEGRAM_ADMIN_HANDLE: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.config.telegramToken }}
  TELEGRAM_TOKEN: {{ . | b64enc }}
  {{- end }}
