name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.1

      - name: Add repositories
        run: |
          for dir in $(ls -d charts/*/); do
            helm dependency list $dir 2> /dev/null | tail -n +2 | head -n -1 | awk '{ print $1 " " $3 }' | while read name url; do
              if helm repo list | grep -q "^$name\s"; then
                echo "Repository name $name already exists, skipping."
              elif helm repo list | awk '{print $3}' | grep -q "^$url$"; then
                echo "Repository URL $url already added, skipping."
              else
                helm repo add $name $url
              fi
            done
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
